# -*- coding: utf-8 -*-
"""stream-diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1And_ACuxJadrDJo54oB2zEVF0cC8xYds
"""

# prompt: buatkan saya user interface streamlit untuk model yang saya bangun ini

import numpy as np
# Import the necessary libraries
import streamlit as st

# Define the main function
def main():
    # Create a title for the application
    st.title('Diabetes Prediction App')

    # Get the input features from the user
    age = st.number_input('Age', min_value=18, max_value=100)
    gender = st.selectbox('Gender', ['Male', 'Female'])
    polyuria = st.selectbox('Polyuria', ['Yes', 'No'])
    polydipsia = st.selectbox('Polydipsia', ['Yes', 'No'])
    weakness = st.selectbox('Weakness', ['Yes', 'No'])
    visual_blurring = st.selectbox('Visual Blurring', ['Yes', 'No'])
    obesity = st.selectbox('Obesity', ['Yes', 'No'])

    # Convert the input features to a list
    input_data = [age, gender, polyuria, polydipsia, weakness, visual_blurring, obesity]

    # Convert the input list to a NumPy array
    input_data_as_numpy_array = np.asarray(input_data)

    # Reshape the NumPy array to a single instance with multiple features
    input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

    # Make predictions using the loaded model
    prediction = model.predict(input_data_reshaped)

    # Print the prediction
    if prediction[0] == 0:
        st.write('The person is not diabetic')
    else:
        st.write('The person is diabetic')

# Call the main function
if __name__ == '__main__':
    main()